### ISSUE TITLE
Feature flags are fetched before the $identify event

### ISSUE THREAD

**Issue by haritowa** [PostHog/posthog-ios#358]
### Version

3.27.0

### Steps to Reproduce

1. Send identify event
2. Observe API calls order

![Image](https://github.com/user-attachments/assets/09f4f4a9-4d00-46b7-9fa4-593dcc1930d5)

### Expected Result

Feature flags are reloaded after the persona created and identified

### Actual Result

Feature flags are reloaded before the persona created and identified which breaks flag persistence(wrong flags are returned as a response to this call)

**Comment by haritowa** [comment]
I see two possible solutions here:
- add a flush invocation right before `remoteConfig?.reloadFeatureFlags()` in identify event
- somehow subscribe for sent events and reload flags on each identify, set and so on

While the second solution seems less hacky, I think the flush "fix" will actually be better, because it enforces proper timeline (identify and immediate flags reload, not identify...pause for batch aggregation...flags reload)

Yet I am not sure how will it behave on bad connection or other events sending failures

**Comment by haritowa** [comment]
I already working on a fix, but to speed up things you can describe which properties from config and manager should I check before feature flag calls on identify and alias

As far as I understand, on set we can't call feature flags because backend processes persona updates in async way

Also I haven't touched group related logic and reset method

**Comment by haritowa** [comment]
@wowrumal @ioannisj draft PR is ready, let's make the initial review and continue the discussion in the PR itself

**Comment by haritowa** [comment]
☝ @ioannisj 

Also I think we already tested with our fix and no wrong feature flags are returned

**Comment by haritowa** [comment]
By the way, I think my PR could be adjusted to accommodate groups and $set events too(gather their data and use for feature flag requests). I decided not to do it to not break stuff(currently $set events are not reloading flags at all and I think users got used to it)

My PR allows us to monitor all this kind of activity in one place and act accordingly. We can discuss it too if you wish

**Comment by wowrumal** [comment]
At the moment we don't have feature flags that depend on people properties

**Comment by haritowa** [comment]
We will test props based flags now both for flags and decide

**Comment by haritowa** [comment]
Yeah, the race condition is present for props related flags. Can make another pr with manual props propagation, yet I don't understand how will it work with
- persistence 
- props that are set from outside. How can we detect it and remove our local override?

**Comment by andyzzhao** [comment]
I am able to replicate the error only in prod with the following steps:
1. Create a flag with two variants and rolled out 100%
2. Call Identify with `distinct_id=authenticated_user` and `$anon_distinct_id=anonymous_user`
3. Call `/flags` with `distinct_id=unauthenticated_user` and `$anon_distinct_id=anonymous_user` returns `control`
4. Call `/flags` with `distinct_id=authenticated_user` and `$anon_distinct_id=anonymous_user` returns `shop`

When I do steps 2 to 3 again with different ids but with `/decide` the variant is consistent. However, subsequent requests to flags with `distinct_id=unauthenticated_user` and `distinct_id=authenticated_user` return a consistent variant. I think #34127 will solve this but if you're seeing the wrong variant on subsequent requests as well then there is something else wrong.

**Comment by andyzzhao** [comment]
I confirmed that https://github.com/PostHog/posthog/pull/34127 solves the issue I described [above](https://github.com/PostHog/posthog-ios/issues/358#issuecomment-3002204024) but @haritowa can you confirm if you are still experience your issue.

**Comment by haritowa** [comment]
@andyzzhao (sorry for the ping, not sure you will see my message otherwise)

**Comment by andyzzhao** [comment]
> Do you want me to perform the same tests again? Have you released new BE and want us to test the changes? I can create isolated api based tests and check it

I want to know if the issue described [here](https://github.com/PostHog/posthog-ios/issues/358#issuecomment-2995549491) was solved. I did my own test to verify the change but I may have misunderstood what the expected behaviour is.

**Comment by andyzzhao** [comment]
> Have your releases a new BE

Yep I made a change to the `/flags` endpoint here https://github.com/PostHog/posthog/pull/34127

**Comment by wowrumal** [comment]
@andyzzhao @ioannisj  
I've tested this case on `us.posthog` and it seems to work as expected 7/7 times (or just lucky :))
But I've also checked this case on `eu.posthog` and looks like the problem is still there
Did you update BE on both environments or just US?

**Comment by wowrumal** [comment]
@haritowa @andyzzhao @ioannisj 
I've checked case on `eu.posthog` one more time. Great news, now it works 5/5 times! 🥳

**Comment by haritowa** [comment]
@andyzzhao @ioannisj 

So looks like we can close this issue. Later I'll create another one for local props, yet we are not blocked with them right now, so it may take a while
